EBank/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
        path('<str:gameName>',views.Balance,name='Balance'),
        path('<str:gameName>/pay',views.payMoney,name='payMoney'), 
]

Games/urls.py
from django.contrib import admin
from django.urls import  path

from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('addGame',views.addGame,name='addGame'),
    path('<str:game_name>/players',views.players,name='players'),
    path("delete/<int:pk>/<str:gameName>/", views.deletePlayer, name="deletePlayer"),
    path("add/<str:gameName>/", views.addPlayer, name="addPlayer"),
    path('games',views.gamesList,name='gamesList'), 
]

inventory/urls.py
from django.contrib import admin
from django.urls import  path

from . import views

urlpatterns = [
    # urls used in Games app for reference
    # path('',views.index,name='index'),
    # path('addGame',views.addGame,name='addGame'),
    # path('<str:game_name>/players',views.players,name='players'),
    # path("delete/<int:pk>/<str:gameName>/", views.deletePlayer, name="deletePlayer"),
    # path("add/<str:gameName>/", views.addPlayer, name="addPlayer"),
    # path('games',views.gamesList,name='gamesList'), 
]

monopolyEbank/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('Games.urls')),
    path('bank/',include('EBank.urls')),
    path('admin/', admin.site.urls),
    path('inventory/', include('inventory.urls')),
]

EBank/models.py
from django.db import models

from Games.models import games



class player(models.Model):
    playerName = models.CharField(max_length=50)
    money = models.PositiveIntegerField(default=1500)
    getOutOFJail = models.PositiveIntegerField(default=0)
    game =  models.ForeignKey(to=games, on_delete = models.CASCADE, default="", editable=False, null=True)

    class Meta:
        unique_together = (('playerName', 'game'),)

    def __str__(self):
        return self.playerName

class deed(models.Model):
    propertyName = models.CharField(max_length=50)
    cost = models.PositiveIntegerField()
    rent =  models.PositiveIntegerField()
    color =  models.CharField(max_length=10)
    houses = models.PositiveIntegerField()
    hotels = models.PositiveIntegerField()
    Owner =  models.OneToOneField(player,on_delete = models.CASCADE, related_name='owner') 
    currentPlayer =  models.ForeignKey(to=player, on_delete = models.CASCADE,related_name='current_player', default=None)
    def __str__(self):
        return self.propertyName

Games/models.py
from django.db import models
from datetime import  datetime


# Create your models here.
class games(models.Model):
    id = models.IntegerField(primary_key=True)
    gameName = models.CharField(max_length=50,unique = True)
    result = models.CharField(max_length=10)
    created_at = models.DateTimeField(default=datetime.now)
    def __str__(self):
        return self.gameName

inventory/models.py
from django.db import models

# Create your models here.

Games/forms.py
from django import forms
from django.forms import ModelForm
from EBank.models import player
from .models import games
from django.forms.widgets import TextInput,Textarea


class playerForm(forms.ModelForm):
    class Meta:
        model = player
        fields=('playerName',)
        labels = {
            'playerName': ('Player Name'),
        }
        widgets = {
            'playerName': forms.TextInput(attrs={'class': 'todo-form shadow-sm bg-transparent border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', #appearance-none bg-transparent border-none text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none',
                                                'id':'playerName',
                                            },),
        }
        


class gameForm(forms.ModelForm):
    class Meta:
        model = games
        fields=('gameName',)
        widgets={
            'gameName':TextInput(attrs={'class': 'form-control',
                                        'placeholder':'Game name',
                                        'onkeyup': 'success()',
                                        'id':'gameName',
                                        'name':'gameName', 
                                        }),

            }
    def __init__(self, *args, **kwargs): 
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['gameName'].label = ''

EBank/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from Games.models import games

from .models import player

# Create your views here.
def Balance(request,gameName):
    context = {}
    currentGame = games.objects.get(gameName=gameName)
    context['gameName'] = gameName
    context['playersList'] = player.objects.filter(game__id=currentGame.id) 
    return render(request,'bank.html',context) 

def payMoney(request,gameName):
    payee_id = request.POST['payee']
    payer_id = request.POST['payer']
    amount = request.POST['amount']
    successT = True
    if amount:
        if payer_id!='Bank':
            payer = player.objects.get(id = payer_id)
            if payer.money > int(amount):
                payer.money= payer.money - int(amount)
                payer.save()
            else:
                successT = False
        if payee_id!='Bank' and successT:
            payee = player.objects.get(id = payee_id)
            payee.money= payee.money + int(amount)
            payee.save()
    return HttpResponseRedirect(f'../{gameName}')

    

Games/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import games
from EBank.models import player
from .forms import playerForm, gameForm
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError



def index(request):
    if(games.objects.first()):
        hasGame =True
    else:
        hasGame =False
    form = gameForm()
    context = {
        'hasGame':hasGame,
        'form':form
    }
    return render(request, 'index.html',context)


def addGame(request):
        if request.method=='POST':
            game_name = request.POST['gameName']
            bool = games.objects.filter(gameName=game_name).first()
            if games.objects.filter(gameName=game_name).first():
                return HttpResponseRedirect(f'/{game_name}/players') 
            game = games(gameName=game_name)
            game.save()
        return HttpResponseRedirect(f'/{game_name}/players') 


def players(request,game_name):
    form = playerForm()
    currentGame = games.objects.get(gameName=game_name)
    context = {
        "form": form,
        'gameName':game_name,
        'message': '',
    }
    context['players_list'] = player.objects.filter(game__id=currentGame.id) 
    return render(request, 'players.html',context)





def deletePlayer(request, pk, gameName):
    form = playerForm()
    player_object = player.objects.get(id=pk)
    player_object.delete()
    return redirect(f"../../../{gameName}/players") #FIX THIS


def addPlayer(request,gameName):
    form = playerForm()
    playerName = request.POST['playerName']
    context = {
        "form": form,
        'gameName':gameName,
        'message': '',
    }
    currentGame = games.objects.get(gameName=gameName)
    try:
        new_player = player.objects.create(playerName = playerName, game = currentGame)
        new_player.save() 
    except ObjectDoesNotExist or IntegrityError:
        print('not player')
    # except IntegrityError:
    #     print('not player')        
    return redirect(f"../../../{gameName}/players") #FIX THIS


def gamesList(request):
    context = {}
    gamesList = games.objects.all()
    context['gamesList'] = gamesList
    return render(request,'games.html',context)

inventory/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from Games.models import games
from EBank.models import player
# from .forms import playerForm, gameForm
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
# Create your views here.

EBank/templates/bank.html
{% extends 'base.html' %}

{% block head%}
BANK
{% endblock %}

{% block content %}

</table>
<form id='transactions-form' action="{{gameName}}/pay" method="post">
    {% csrf_token %}
    <select id="payer" name="payer">
        {% for player in playersList %}
        <option value="{{player.id}}">{{player.playerName}}</option>
        {% endfor %}
        <option value="Bank">Bank</option>
    </select>
    <label for="payee"> =></label>
    <select id="payee" name="payee">
        {% for player in playersList %}
        <option value="{{player.id}}">{{player.playerName}}</option>
        {% endfor %}
        <option value="Bank">Bank</option>
    </select>
    <input id="amount", name='amount' type='number'/>
    <button type="submit" >pay</button> 
    </form>


{% endblock %}



{% block scripts %}
$(document).on('submit','#transactions-form',function(e){
  e.preventDefault();

  $.ajax({
    type:'POST',
    url:'{{gameName}}/pay',
    data:{
        payee:$('#payee').val(),
        payer:$('#payer').val(),
        amount:$('#amount').val(),
      csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
    },
    success: function(data){
    }
  });
  document.getElementById('amount').value = ''
});
{% endblock %}

Games/templates/base.html
<!DOCTYPE html>
<html lang="en" style="height:100%">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    {% block head %} head here {%endblock%}

    <title>{%block title %} Title here {%endblock%}</title>
</head>
{%block content %} content here {% endblock %}
</body>
<script>
{% block scripts %}  {% endblock %}
</script>
</html>

Games/templates/games.html
{% extends 'base.html' %}

{% block title %}
Monopoly - Games
{% endblock %}

{%block head %}
{% load static %}
<script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'Games/games.css' %}">
{% endblock %}


{% block content %}
{% load static %}
</ul>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex justify-content-between align-items-center activity">
                <img class = "ml-2" src="{% static 'Games/monopolyLogo.png' %}"  style="max-height:30px; width: auto;">
                <div class="activity-done"><h3>Saved Games</h3></div>
                <div class="icons"><i class="fas fa-search mr-4"></i> <i class="fa fa-ellipsis-h mr-4" aria-hidden="true"></i></div>
            </div>
            {%if gamesList %}
            {% for game in gamesList %}
            <div class="mt-3">
                <ul class="list list-inline">
                    <li class="d-flex justify-content-between">
                        <div class="d-flex flex-row align-items-center"> 
                            <div class="ml-2">
                                <a href='./bank/{{game}}'><h6 class="mb-0">{{game.gameName}}</a> 
                                <div class="d-flex flex-row mt-1 text-black-50 date-time">
                                    <div><i class="fa fa-calendar" aria-hidden="true"></i><span class="ml-2">{{game.created_at}}</span></div>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex flex-row align-items-center">
                            <div class="d-flex flex-column mr-2">
                                <div class="profile-image">
                                {% for player in game.player_set.all %}
                                <img class="rounded-circle" src="https://avatars.dicebear.com/api/open-peeps/{{player.id}}.svg" width="30">
                                {% endfor %}
                                <span><i class="fa fa-trash ml-3"></i></span>
                        </div>
                    </li>
                </ul>
            </div>   
            {% endfor %}
            {% else %}
                <div class="row d-flex justify-content-center ml-4 "><a href='../'> <h1>Create a game </a> </h1></div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

Games/templates/index.html
{% extends 'base.html'%} 
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'Games/index.css' %}">
{% endblock %} 

{% block title %} 
Monopoly - Game
{% endblock %} 


 {% block content %}

  {% load static %}
<body>
  <div class="vertical-center">
    <div class="container d-flex p-2 justify-content-center">
      <div class="card">
        <div class="d-flex align-items-center logo-container">
          <img
            class="card-img-top"
            style="width: 100%; height: auto;"
            src="{% static 'Games/monopolyLogo.png' %}"
            alt=""
          />
        </div>
        <div class="card-body form-container d-flex align-items-end justify-content-center">
          <form action="/addGame" method="post" class="mt-auto p-2">
            {% csrf_token %} {{form}}<br />
            <button
              id="startGame"
              type="submit"
              class="btn btn-success btn-lg"
              disabled
            >
              Start
            </button>
            <button
              id="loadGame"
              type="button"
              class="btn btn-dark btn-lg"
              {%
              if
              hasGame%}
              disabled
              {%
              endif%}
            >
              <a href="/games">
                Load
              </a>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="color-border"></div>

  {% endblock %} {%block scripts %} function success() {
  if(document.getElementById("gameName").value==="") {
  document.getElementById('startGame').disabled = true; } else {
  document.getElementById('startGame').disabled = false; } } {% endblock %}
</body>

Games/templates/players.html
{% extends 'base.html'%} {% block head %} {% load static %}
<script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
<link
  href="{% static 'fontawesome_free/css/all.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'fontawesome_free/css/fontawesome.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'fontawesome_free/css/brands.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'fontawesome_free/css/solid.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"
></script>
<link rel="stylesheet" href="{% static 'Games/players.css' %}">
{% endblock %}
 {% block title %} Monopoly - Players {% endblock %}
 {% block content %} 
 {% load static %}
<body>
  <a href= '../../'><i class="fas fa-chevron-circle-left fa-2x back"></i></a>
  <div class="vertical-center">
    <div class="container d-flex p-2 justify-content-center">
      <div class="card maincard">
        <div class="img-cont text-center">
          <img
            class="card-img-top"
            src="{% static 'Games/monopolyLogo.png' %}"
            alt=""
          />
        </div>

        <div class="card-body">
          <div id="gamename" class="gamename">{{gameName}}</div>
          <div class="form-list-container">
            <form
              action='{% url "addPlayer" gameName=gameName %}'
              method="post"
            >
              {% csrf_token %} {% for field in form %}
              <!-- <label class="todo-form" for="{{ field.auto_id }}">{{ field.label }} 1</label> -->
              {{ field }} {% endfor %}
              <!-- {{form}}  -->
              <button type="submit"><i class="fas fa-user-plus"></i></button
              ><br />
              {{message}}
            </form>
            <div class="card playerCard" >
              <ul class="list-group list-group-flush playerList">
                {% for player in players_list reversed %}
                <li class="list-group-item align-middle">
                  <img
                    class="w-12 h-10 rounded-full float-left"
                    src="https://avatars.dicebear.com/api/open-peeps/{{player.id}}.svg"
                    alt=""
                  />
                  {{player}}
                  <div class="w-10 h-10 float-right">
                    <a
                      href="{% url 'deletePlayer' pk=player.id gameName=gameName %}"
                    >
                      <i class="fas fa-trash-alt"></i
                    ></a>
                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="color-border"></div>
</body>

{% endblock %} {% block scripts %}
$(document).on('submit','#player-form',function(e){ e.preventDefault(); $.ajax({
type:'POST', url:'/addPlayer', data:{ player:$('#playerName').val(),
game:$('#gamename').text(),
csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(), }, success:
function(data){
<!-- alert(data) -->
} }); document.getElementById('playerName').value = '' }); {% endblock %}

inventory/templates/base.html
<!DOCTYPE html>
<html lang="en" style="height:100%">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block head %} head here {%endblock%}
    <title>{%block title %} Title here {%endblock%}</title>
</head>
{%block content %} content here {% endblock %}
</body>
<script>
{% block scripts %} scripts here {% endblock %}
</script>
</html>

inventory/templates/inventory.html
{% extends 'base.html' %}

{% block title %}
Player Inventory
{% endblock %}

%block head %}
<style>

</style>

{% endblock %}

% block content %}
<!-- <h3>SAVED GAMES</h3>
<ul>
    {% for game in gamesList %}
    <li>
    <a href='./{{game}}/players'>{{game.gameName}}</a>|
    <a href='./bank/{{game}}'> bank</a>  
    <!-- add delete game button -->
    </li>
    {% endfor %}

</ul> -->

{% endblock %}

templates/games.html
{% extends 'base.html' %}

{% block title %}
Monopoly - Games
{% endblock %}

{%block head %}
<style>
    a{
        /* text-decoration: none; */
        color:red;
    }
</style>

{% endblock %}


{% block content %}
<h3>SAVED GAMES</h3>
<ul>
    {% for game in gamesList %}
    <li>
    <a href='./{{game}}/players'>{{game.gameName}}</a>|
    <a href='./bank/{{game}}'> bank</a>
    </li>
    {% endfor %}

</ul>

{% endblock %}